### ISSUE TITLE
Screenshot 

### ISSUE THREAD

**Issue by marekspisiak** [ErAz7/Jonin#2]
Hi i am traying to make screenshot of target but i am still getting black screen. Does windows have some kind of protection against desktop screenshot or do you know some way how to do it ?

**Comment by ErAz7** [comment]
This is because of security protection from Windows. It's called [secure desktop](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-switch-to-the-secure-desktop-when-prompting-for-elevation):


There might be some workaround to turn this off if you have admin access to target (Ninja process is running as admin) but needs more investigation to find a working approach

However, surprisingly, Windows allows you to access and record webcam and mic very easily (e.g. using FFmpeg); [Here is a working approach](https://github.com/ErAz7/Jonin#record-ninja-camera-and-mic)

**Comment by marekspisiak** [comment]
I turned it off because I have physical access to target system but it is still not working. And yes I know you can easily record webcam but there is that security light so it is a bit more risky. But if you know how to get around that I would appreciate any guidance. On some commands like ffmpeg gdigrab it is even failing to capture desktop so there is not even black screen. 

```
ffmpeg version 4.4-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[gdigrab @ 000001f3e781e600] Capturing whole desktop as 1024x768x32 at (0,0)
[gdigrab @ 000001f3e781e600] Failed to capture image (error 5)
[gdigrab @ 000001f3e781e600] Could not find codec parameters for stream 0 (Video: bmp, none, 754987 kb/s): unspecified size
Consider increasing the value for the 'analyzeduration' (15000000) and 'probesize' (70000000) options
Input #0, gdigrab, from 'desktop':
  Duration: N/A, bitrate: 754987 kb/s
  Stream #0:0: Video: bmp, none, 754987 kb/s, 30 fps, 1000k tbr, 1000k tbn, 1000k tbc
Output #0, matroska, to 'pipe:':
Output file #0 does not contain any stream
```

**Comment by ErAz7** [comment]
yes I've also tried turning it off but still Windows blocks access to desktop, it seems simply turning it off in control panel is not enough to disable it. Mybe you consider trying steps here:
https://www.windowscentral.com/how-enable-desktop-access-during-user-account-control-prompt-windows-10
and about FFmpeg command, the reason is the same

anyways, this is not related to this project and it's an OS-related behavior for all elevated (background) processes, thus closing the issue. Please feel free to share your solutions here as some users of the project would need it
